"""Walking skeleton for the six-stage Track 2 review pipeline.

M0 intentionally performs no substantive review analysis.  It does, however,
validate and freeze the inputs, execute every stage in order, and produce the
complete official output shape so later milestones can replace one stage at a
time without changing the command-line contract.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from hashlib import sha256
from pathlib import Path
from typing import Callable


STAGE_NAMES = (
    "S1 parse",
    "S2 claims",
    "S3 mech-check",
    "S4 verdicts",
    "S5 compose",
    "S6 freeze",
)


@dataclass
class ReviewState:
    """Mutable state passed through the ordered pipeline stages."""

    paper_path: Path
    evidence_dir: Path
    output_path: Path
    paper_hash: str = ""
    evidence_hashes: list[tuple[str, str]] = field(default_factory=list)
    completed_stages: list[str] = field(default_factory=list)
    review_markdown: str = ""


def _sha256_file(path: Path) -> str:
    digest = sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def _evidence_hashes(evidence_dir: Path) -> list[tuple[str, str]]:
    files = sorted(path for path in evidence_dir.rglob("*") if path.is_file())
    return [
        (path.relative_to(evidence_dir).as_posix(), _sha256_file(path))
        for path in files
    ]


def _mark_stage(state: ReviewState, name: str) -> ReviewState:
    """Record a no-op stage so stage order is observable and testable."""

    state.completed_stages.append(name)
    return state


def _freeze_inputs(state: ReviewState) -> ReviewState:
    # Hash once before S1 and verify again at S6 so a mid-run input mutation is
    # never silently accepted as part of the frozen review identity.
    if state.paper_hash != _sha256_file(state.paper_path):
        raise RuntimeError("paper changed while the review pipeline was running")
    if state.evidence_hashes != _evidence_hashes(state.evidence_dir):
        raise RuntimeError("evidence bundle changed while the review pipeline was running")
    return _mark_stage(state, "S6 freeze")


def _format_evidence_identity(state: ReviewState) -> str:
    if not state.evidence_hashes:
        return f"`{state.evidence_dir}` (empty directory)"
    entries = ", ".join(f"`{name}` (`sha256:{digest}`)" for name, digest in state.evidence_hashes)
    return f"`{state.evidence_dir}`: {entries}"


def _compose_scaffold_review(state: ReviewState) -> str:
    """Return the official review shape with honest M0-only content."""

    stage_trace = " -> ".join(STAGE_NAMES)
    return f"""# Track 2 — ICML-Style Review

## Paper and Evidence Identity

- Review Agent name/version: No Free Lunch Review Agent / `m0-scaffold`
- `review-agent.md` path/hash: Not frozen in M0
- Paper version/hash: `{state.paper_path}` / `sha256:{state.paper_hash}`
- Evidence bundle reviewed: {_format_evidence_identity(state)}

## Summary

M0 walking-skeleton run completed. No substantive paper analysis is performed at this milestone.

## Strengths

- Not assessed by the M0 walking skeleton.

## Weaknesses

- Not assessed by the M0 walking skeleton.

## Questions for the Authors

- None generated by the M0 walking skeleton.

## Scores

- Soundness: Not scored — S3 and S4 are no-op stages in M0, so there are no mechanical findings or claim verdicts to support a score.
- Presentation: Not scored — S1 does not yet parse paper structure in M0, so presentation evidence is unavailable.
- Contribution: Not scored — S2 does not yet extract claims in M0, so contribution evidence is unavailable.
- Overall recommendation: Not scored — the M0 pipeline produces no substantive findings from which to derive a recommendation.
- Confidence: Not scored — no claims are evaluated for verifiability in M0.

## Ethics and Limitations

This scaffold must not be treated as a substantive review. It makes no claims about the paper and performs no citation, injection, ethics, or evidence-quality checks.

## Evidence Trace

- Pipeline execution: `{stage_trace}`.
- Frozen paper input: `{state.paper_path}` (`sha256:{state.paper_hash}`).
- No central paper claims were extracted or evaluated in M0.
"""


class ReviewPipeline:
    """Execute the S1-S6 walking skeleton in the specified order."""

    def __init__(self) -> None:
        self._stages: tuple[Callable[[ReviewState], ReviewState], ...] = (
            lambda state: _mark_stage(state, "S1 parse"),
            lambda state: _mark_stage(state, "S2 claims"),
            lambda state: _mark_stage(state, "S3 mech-check"),
            lambda state: _mark_stage(state, "S4 verdicts"),
            self._compose,
            _freeze_inputs,
        )

    @staticmethod
    def _compose(state: ReviewState) -> ReviewState:
        state.review_markdown = _compose_scaffold_review(state)
        return _mark_stage(state, "S5 compose")

    def run(self, paper_path: Path, evidence_dir: Path, output_path: Path) -> ReviewState:
        paper_path = paper_path.expanduser().resolve()
        evidence_dir = evidence_dir.expanduser().resolve()
        output_path = output_path.expanduser().resolve()

        if not paper_path.is_file():
            raise FileNotFoundError(f"paper is not a file: {paper_path}")
        if not evidence_dir.is_dir():
            raise NotADirectoryError(f"evidence directory does not exist: {evidence_dir}")
        if output_path == paper_path:
            raise ValueError("output path must differ from the paper path")

        state = ReviewState(
            paper_path,
            evidence_dir,
            output_path,
            paper_hash=_sha256_file(paper_path),
            evidence_hashes=_evidence_hashes(evidence_dir),
        )
        for stage in self._stages:
            state = stage(state)

        if tuple(state.completed_stages) != STAGE_NAMES:
            raise RuntimeError(f"pipeline stage order mismatch: {state.completed_stages}")

        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(state.review_markdown, encoding="utf-8")
        return state


def run_pipeline(paper_path: Path, evidence_dir: Path, output_path: Path) -> ReviewState:
    """Convenience entry point for callers embedding the reviewer package."""

    return ReviewPipeline().run(paper_path, evidence_dir, output_path)
